In [2]:
##c tem função de combinar

x <- c(5,6,7,8)
is.vector(x)
x

[1] TRUE

[1] 5 6 7 8

In [3]:
x <- c(9:12)
is.vector(x)
x

[1] TRUE

[1]  9 10 11 12

In [9]:
##matrix true preenche horizontalmente
x <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = TRUE)
x

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [11]:
##matrix false preenche verticalmente
x <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 3, byrow = FALSE)
x

[,1] [,2] [,3]
[1,] 1    4    1   
[2,] 2    5    2   
[3,] 3    6    3

In [12]:
##sem byrow ele preenche verticalmente por padrao
x <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 3)
x

[,1] [,2] [,3]
[1,] 1    4    1   
[2,] 2    5    2   
[3,] 3    6    3

In [13]:
#Gera matriz numerica de 5x4

y<- matrix (01:20, nrow = 5, ncol =4)
y

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [17]:
# identificar colunas ou elementos ##colchetes ordem [LINHA, COLUNA]
y [5,3] #coluna de matriz
y [3,]

[1] 15

[1]  3  8 13 18

In [25]:
celulas <- c(1,26,24,68)
nomeslinhas <- c("R1","R2")
nomescolunas <- c("C1","C2")

minhamatriz <- matrix(celulas, nrow = 2, ncol = 2, byrow = TRUE, dimnames = list(nomeslinhas,nomescolunas))
minhamatriz

C1 C2
R1  1 26
R2 24 68

In [1]:
X <- function(a,b){ 

  a * b 

} 

is.integer(X(5,2))
x

[1] FALSE

ERROR: ignored

In [2]:
X <- c (1:10) 

X [c (TRUE, FALSE, T, T, FALSE, F, F, F, TRUE, T)] 

[1]  1  3  4  9 10

In [3]:
X <- c (1:10) 

X >= 8 

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE

In [4]:
X <- c (1:10) 

X < 5 

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE

In [5]:
X <- c (1:10) 

X [(X > 8) | (X < 5)] 

[1]  1  2  3  4  9 10

In [12]:
X <- c (1:10) 

X [(X<8)&(X>5)] 

[1] 6 7